name: EVM/RPC

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ETHLIBS_TEST_WS_URL: wss://goerli.infura.io/ws/v3/
  AUTH_ID: ${{ secrets.INFURA_PROJECT_ID }}
  AUTH_PASS: ${{ secrets.INFURA_API_KEY }}

jobs:
  rpc-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: go test -v ./node/rpc_test.go
